### ISSUE TITLE
React guide

### ISSUE THREAD

**Issue by mahenth** [academind/react-complete-guide-code#10]
![Screenshot 2021-05-05 104713](https://user-images.githubusercontent.com/81411626/117099659-58ff7f80-ad8f-11eb-9aff-7b0076fa0747.png)
please check my code error and help to clear.

**Comment by gokulyc** [comment]
props.item is undefined , are you sending list object to props. 

Also why there is two types props.item and props.items ???

**Comment by mahenth** [comment]
> props.item is undefined , are you sending list object to props.
> 
> Also why there is two types props.item and props.items ???

no only one props item
